# Generated by Django 3.0.7 on 2020-06-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisers',
            name='type_user',
            field=models.IntegerField(blank=True),
        ),
    ]
