# Generated by Django 3.0.7 on 2020-06-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20200613_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisers',
            name='document_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='advisers',
            name='document_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
